fix: show relative path when logging i18n strings output destination
dhis2/app-platform pull request #540
Opened 2021-03-24 12:00 UTC by mediremi

Currently, when generating `i18n` strings (either as a result of `d2-app-scripts start` or `d2-app-scripts extract`), a message in the format below is logged:

```
Writing N language strings to .//home/user/some/path/app-being-developed/i18n/en.pot...
```

This PR ensures that the path to `en.pot` logged is relative to the current working directory, resulting in the more consice:

```
Writing N language strings to ./en.pot...
```

2021-03-24 12:43 UTC, amcgee approved these changes
LGTM

i see there's actually an existing bug here - the CLI commands accept a `--cwd` argument, so `process.cwd()` is NOT always guaranteed to be the proper cwd.  This function should probably accept `paths` which includes the `cwd` arg (defaulting to `process.cwd()`) and use that instead - as is currently written, this change looks correct.  Feel free to fix the larger issue if desired, but if we want to defer the bugfix (likely also in `generate` as both were ported from https://github.com/dhis2/d2-i18n-generate / https://github.com/dhis2/d2-i18n-extract) we just can create an issue to follow up.

2021-03-24 14:09 UTC, mediremi commented
I'll update both `extract` and `generate` so that they use `paths.cwd` instead of `process.cwd()` :+1:

2021-03-29 23:23 UTC, amcgee requested changes

2021-03-29 23:23 UTC, amcgee commented on cli/src/commands/i18n.js
> -        },
This makes this a breaking change, unfortunately - we need to keep the `path` and `output` options for backwards compatibility but fall back to `paths.i18nStrings` and `paths.i18nLocales` below

2021-04-27 07:39 UTC, amcgee approved these changes

2021-04-27 07:40 UTC, merged