chore(deps): update shell to ui@9
dhis2/app-platform pull request #824
Opened 2024-01-16 14:26 UTC by Birkbjo

BREAKING CHANGE: Updated major version of UI

2024-01-25 19:51 UTC, kabaros approved these changes

2024-01-26 16:09 UTC, KaiVandivier requested changes
I think this needs to be released as a breaking change because it will actually break builds unless the consumer changes something (upgrades the rest of the app to `ui`@9 or uses a resolution) -- here's an example of an app with a dependency on `ui@^8`:

<img width="668" alt="Screenshot 2024-01-26 at 5 07 37 PM" src="https://github.com/dhis2/app-platform/assets/49666798/b124da06-c110-4247-ba2c-2e8e4fd61335">

2024-01-30 11:41 UTC, Birkbjo commented
@KaiVandivier The commit has `breaking change`, so it would be a major version bump.

2024-01-30 12:37 UTC, KaiVandivier approved these changes

2024-03-05 07:30 UTC, merged